"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRight, AudioLines, Heart, Play, Pause, Search, X, LoaderCircle, RotateCcw, Info, Check, SkipForward, Volume2 } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import featuredData from "@/lib/featured.json";
import { Track, trackKey, seconds, providerName } from "@/lib/music";
type ApiData={error?:string;login?:boolean;tracks:Track[];track:Track;candidateCount:number;elapsedMs:number;model:string};
type Direction="close"|"sideways"|"bold";
const featured=featuredData as Track[];
const directions:[Direction,string,string][]=[["close","沿着喜欢","优先寻找资料关联更近的作品"],["sideways","换个角度","换一位歌手，保留探索起点"],["bold","再大胆一点","试试关联路径以外的编辑探索"]];
function readStored(key:string,fallback:any){try{return JSON.parse(localStorage.getItem(key)||"null")??fallback;}catch{return fallback;}}
export default function Home(){
 const [view,setView]=useState("discover");const [query,setQuery]=useState("");const [searchResults,setSearchResults]=useState<Track[]|null>(null);const [searching,setSearching]=useState(false);
 const [seed,setSeed]=useState<Track|null>(null);const [direction,setDirection]=useState<Direction>("close");const [notes,setNotes]=useState("");const [recommendations,setRecommendations]=useState<Track[]|null>(null);const [round,setRound]=useState(0);const [busy,setBusy]=useState(false);const [stage,setStage]=useState("正在寻找相关歌曲");
 const [saved,setSaved]=useState<Track[]>([]);const [dismissed,setDismissed]=useState<Track[]>([]);const [hydrated,setHydrated]=useState(false);const [error,setError]=useState("");const [login,setLogin]=useState(false);const [toast,setToast]=useState("");const [meta,setMeta]=useState<{candidateCount:number;elapsedMs:number;model:string}|null>(null);
 const [current,setCurrent]=useState<Track|null>(null);const [playing,setPlaying]=useState(false);const [loadingTrack,setLoadingTrack]=useState("");const [position,setPosition]=useState(0);const [duration,setDuration]=useState(30);const [volume,setVolume]=useState(.7);
 const audioRef=useRef<HTMLAudioElement|null>(null);const playbackId=useRef(0);const requestRef=useRef<AbortController|null>(null);const searchRef=useRef<AbortController|null>(null);const searchInput=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{setSaved(readStored("aftertone-saved",[]));setDismissed(readStored("aftertone-dismissed",[]));try{const s=sessionStorage.getItem("aftertone-seed");if(s)setSeed(JSON.parse(s));}catch{}setHydrated(true);return()=>{requestRef.current?.abort();searchRef.current?.abort();};},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem("aftertone-saved",JSON.stringify(saved.map(({preview,...t})=>t)));localStorage.setItem("aftertone-dismissed",JSON.stringify(dismissed.map(({preview,...t})=>t)));}catch{setToast("浏览器存储不可用，收藏只保留到本次页面关闭。");}},[saved,dismissed,hydrated]);
 useEffect(()=>{if(!hydrated)return;try{seed?sessionStorage.setItem("aftertone-seed",JSON.stringify(seed)):sessionStorage.removeItem("aftertone-seed");}catch{}},[seed,hydrated]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),3000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(!busy)return;const timer=setTimeout(()=>setStage("Jev 正在逐首筛选"),3500);return()=>clearTimeout(timer);},[busy]);
 const isSaved=(t:Track)=>saved.some(s=>trackKey(s)===trackKey(t));
 function save(t:Track){const exists=isSaved(t);setSaved(prev=>exists?prev.filter(x=>trackKey(x)!==trackKey(t)):[t,...prev]);if(!exists)setDismissed(prev=>prev.filter(x=>trackKey(x)!==trackKey(t)));setToast(exists?"已移出收藏":"这首留下了 · 收藏保存在当前浏览器");}
 function dismiss(t:Track){setDismissed(prev=>[t,...prev.filter(x=>trackKey(x)!==trackKey(t))].slice(0,120));setRecommendations(prev=>prev?.filter(x=>trackKey(x)!==trackKey(t))??null);setToast("已记下，这一首先不推荐了");}
 async function search(q=query){if(q.trim().length<2){setError("输入至少两个字，或试试歌手的名字。");return;}searchRef.current?.abort();const controller=new AbortController();searchRef.current=controller;setSearching(true);setError("");setQuery(q);try{const response=await fetch(`/api/music?q=${encodeURIComponent(q.trim())}`,{signal:controller.signal});const data=await response.json() as ApiData;if(!response.ok)throw Error(data.error);setSearchResults(data.tracks);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"没有搜索成功，请再试一次。");}finally{if(!controller.signal.aborted)setSearching(false);}}
 function choose(t:Track){requestRef.current?.abort();setBusy(false);setSeed(t);setSearchResults(null);setRecommendations(null);setMeta(null);setRound(0);setError("");setView("discover");requestAnimationFrame(()=>document.querySelector(".seed-panel")?.scrollIntoView({behavior:"smooth",block:"center"}));}
 async function recommend(t=seed,excludePrevious=false){if(!t)return;requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setBusy(true);setStage("正在寻找相关歌曲");setError("");setLogin(false);const excluded=[...dismissed,...saved,...(excludePrevious?recommendations||[]:[])].map(trackKey);try{const res=await fetch("/api/recommend",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.signal,body:JSON.stringify({seed:{id:t.id,provider:t.provider},direction,notes,excluded:[...new Set(excluded)].slice(0,150),feedback:{liked:saved.slice(0,8).map(x=>`${x.artist} — ${x.title}`),disliked:dismissed.slice(0,8).map(x=>`${x.artist} — ${x.title}`)}})});const data=await res.json() as ApiData;if(!res.ok){if(data.login)setLogin(true);throw Error(data.error);}setRecommendations(data.tracks);setRound(0);setMeta(data);requestAnimationFrame(()=>document.querySelector(".records")?.scrollIntoView({behavior:"smooth",block:"start"}));}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"这一轮未完成，请再试一次。");}finally{if(!controller.signal.aborted)setBusy(false);}}
 async function play(t:Track){const audio=audioRef.current;if(!audio)return;if(current&&trackKey(current)===trackKey(t)&&audio.src){if(!audio.paused){audio.pause();return;}try{await audio.play();}catch{setError("浏览器暂停了播放，请再次点击试听。");}return;}const version=++playbackId.current;audio.pause();audio.removeAttribute("src");audio.load();setCurrent(t);setPosition(0);setDuration(30);setLoadingTrack(trackKey(t));setError("");try{const response=await fetch(`/api/music?id=${t.id}&provider=${t.provider}`);const data=await response.json() as ApiData;if(version!==playbackId.current)return;if(!response.ok)throw Error(data.error);if(!data.track.preview)throw Error("这首歌暂时没有可用试听，可以前往音乐平台收听。");setCurrent({...t,...data.track});audio.src=data.track.preview;audio.volume=volume;await audio.play();}catch(e){if(version===playbackId.current)setError(e instanceof Error?e.message:"试听暂时不可用，请前往音乐平台收听。");}finally{if(version===playbackId.current)setLoadingTrack("");}}
 const displayTrack=current||seed||featured[0];
 const visible=recommendations===null?featured.slice(0,3):recommendations.slice(round*3,round*3+3);
 function next(){if(recommendations&&(round+1)*3<recommendations.length)setRound(round+1);else recommend(seed,true);}
 function card(t:Track,i:number){const active=current&&trackKey(current)===trackKey(t);return <article className={`record ${active?"is-current":""}`} key={trackKey(t)}><div className="cover-wrap"><img src={t.image} alt={`${t.album} 专辑封面`} loading="lazy"/><span className="record-number">0{i+1}</span>{active&&playing&&<span className="now-playing">正在试听</span>}<button className="cover-play" aria-label={`${active&&playing?"暂停":"试听"} ${t.title}`} onClick={()=>play(t)} disabled={loadingTrack===trackKey(t)}>{loadingTrack===trackKey(t)?<LoaderCircle className="spin" size={23}/>:active&&playing?<Pause fill="currentColor" size={23}/>:<Play fill="currentColor" size={23}/>}</button></div><div className="record-title"><h3>{t.title}</h3><button className={`heart-button ${isSaved(t)?"is-saved":""}`} onClick={()=>save(t)} aria-label={`${isSaved(t)?"取消收藏":"收藏"} ${t.title}`} aria-pressed={isSaved(t)}><Heart size={19} fill={isSaved(t)?"currentColor":"none"}/></button></div><p className="artist">{t.artist}</p>{recommendations!==null&&<p className="reason">{t.reason}</p>}<div className="record-bottom"><span>{t.genre||t.album}</span><a href={t.url} target="_blank" rel="noreferrer" aria-label={`在 ${providerName(t)} 听 ${t.title} 完整版`}>{providerName(t)} <ArrowUpRight size={14}/></a></div><div className="record-actions"><button onClick={()=>{choose(t);}}>{recommendations===null?"从这首出发":"沿着这首继续"}<ArrowRight size={15}/></button>{recommendations!==null&&<button className="quiet" onClick={()=>dismiss(t)}>不太合适</button>}</div>{t.provider==="itunes"&&<p className="attribution">试听 provided courtesy of iTunes</p>}</article>;}
 return <main className="site-shell"><Tabs value={view} onValueChange={setView}>
 <header className="masthead"><a className="wordmark" href="/">aftertone<span>余音</span></a><TabsList variant="line" className="site-nav"><TabsTrigger value="discover">发现音乐</TabsTrigger><TabsTrigger value="saved">我的收藏 <span className="saved-count">{saved.length.toString().padStart(2,"0")}</span></TabsTrigger></TabsList><span className="edition">A PERSONAL LISTENING ROOM</span></header>
 <TabsContent value="discover"><div className={`discovery-stage ${seed?"has-seed":""}`}><div className="search-side"><section className="intro"><div><p className="eyebrow">GOOD MUSIC FINDS A WAY</p><h1>下一首，<br/><em>你的单曲循环。</em></h1></div><div className="intro-aside"><p>从一个熟悉的声音，<br/>走进一片未曾听过的世界。</p></div></section>
 <section className="search-section"><form className="search-form" onSubmit={e=>{e.preventDefault();search();}}><Search size={21}/><input ref={searchInput} aria-label="搜索喜欢的歌" placeholder="你最近反复听的，是哪首歌？" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120}/><button className="primary-button" type="submit" disabled={searching}>{searching?<><LoaderCircle size={16} className="spin"/>搜索中</>:<>找一首歌 <ArrowUpRight size={17}/></>}</button></form><div className="search-hints"><span>试试</span>{["Men I Trust","Radiohead","周杰伦"].map(q=><button key={q} onClick={()=>search(q)}>{q} <ArrowUpRight size={12}/></button>)}</div>
 {searchResults!==null&&<div className="search-results"><div className="results-heading"><span>{searchResults.length?"选一首作为起点 · 注意歌手与录音版本":"没有找到，试试加上歌手名字"}</span><button aria-label="收起搜索结果" onClick={()=>setSearchResults(null)}><X size={18}/></button></div>{searchResults.map(t=><div className="search-row" key={trackKey(t)}><button className="search-art" onClick={()=>play(t)} aria-label={`试听搜索结果 ${t.title}`}><img src={t.image} alt=""/><Play size={15}/></button><button className="search-track-name" onClick={()=>choose(t)}><strong>{t.title}</strong><span>{t.artist} · {t.album}</span></button><span className="search-duration">{seconds(t.duration)}</span><button className="choose-track" onClick={()=>choose(t)} aria-label={`选择 ${t.title} 作为起点`}>选这首 <ArrowUpRight size={15}/></button></div>)}</div>}
 </section></div><div className="art-side" aria-label="今日精选唱片"><div className="art-caption"><span>THE ART OF DISCOVERY</span><span>33⅓ RPM / VOL. 001</span></div><div className={`album-installation ${playing?"is-spinning":""}`}><img className="vinyl-object" src="/images/vinyl-record.jpg" alt=""/><button className="art-sleeve sleeve-main" onClick={()=>play(displayTrack)} aria-label={`试听陈列唱片 ${displayTrack.title}`}><img src={displayTrack.image} alt={`${displayTrack.title} 唱片封面`}/><span>{playing?<Pause size={15} fill="currentColor"/>:<Play size={15} fill="currentColor"/>} {displayTrack.artist}</span></button><span className="art-title">{displayTrack.title}</span></div><div className="art-footnote"><span>CURATED BY CURIOSITY.</span><span>为下一次心动，留一点空白。</span></div></div></div>
 {seed&&<section className="seed-panel"><div className="seed-heading"><div className="seed-identity"><img src={seed.image} alt=""/><div><span className="eyebrow">YOUR STARTING POINT</span><h2>{seed.title}</h2><p>{seed.artist}</p></div></div><button className="icon-button" aria-label="移除起点歌曲" onClick={()=>{requestRef.current?.abort();setBusy(false);setSeed(null);setRecommendations(null);setMeta(null);}}><X size={19}/></button></div><div className="seed-controls"><div className="direction-group" aria-label="探索方向">{directions.map(([key,label,title])=><button key={key} title={title} aria-pressed={direction===key} className={direction===key?"selected":""} onClick={()=>setDirection(key)}>{label}</button>)}</div><button className="primary-button" onClick={()=>recommend()} disabled={busy}>{busy?<><LoaderCircle className="spin" size={17}/>正在找歌</>:<>帮我找歌 <ArrowRight size={17}/></>}</button></div><input className="preference-input" aria-label="补充找歌偏好" placeholder="有特别偏好吗？例如：不要现场版、想听 90 年代的歌（选填）" value={notes} maxLength={200} onChange={e=>setNotes(e.target.value)}/></section>}
 {busy&&<div className="finding" role="status"><AudioLines className="pulse" size={23}/><div><strong>{stage}</strong><p>从真实曲库里挑选，这次值得你听的几首。</p></div><button onClick={()=>{requestRef.current?.abort();setBusy(false);}}>取消</button></div>}
 {error&&<div className="error-message" role="alert"><span>{error}</span>{login&&<a href="/signin-with-chatgpt?return_to=/" target="_top">登录后继续 <ArrowUpRight size={14}/></a>}<button aria-label="关闭提示" onClick={()=>setError("")}><X size={17}/></button></div>}
 <section className={`records ${busy?"is-loading":""} ${recommendations===null?"editorial-picks":"recommendation-picks"}`}><div className="section-heading"><div><span className="eyebrow">{recommendations!==null?"SELECTED FOR YOUR NEXT LISTEN":"SIDE A — START SOMEWHERE"}</span><h2>{recommendations!==null?"听听，这三首":"三个起点，听向别处"}</h2></div><span className="section-note">{recommendations!==null?`${round+1} / ${Math.max(1,Math.ceil(recommendations.length/3))} 组 · Jev 筛选` : "选一首，让它带你去下一站"}</span></div>{visible.length?<div className="record-grid">{visible.map(card)}</div>:<div className="empty-state"><AudioLines size={32}/><h3>这一轮，没有勉强凑数。</h3><p>现有资料不足以支持合适的推荐。换个起点，或者放宽刚才的条件。</p><button onClick={()=>{setRecommendations(null);setNotes("");searchInput.current?.focus();}}>重新找个起点 <ArrowRight size={16}/></button></div>}{recommendations!==null&&recommendations.length>0&&<div className="next-round"><span>{meta?`从 ${meta.candidateCount} 首候选中筛选 · 依据歌曲资料与喜好记录`:""}</span><button className="outline-button" disabled={busy} onClick={next}>{(round+1)*3<recommendations.length?"再听三首":"寻找新一轮"}<ArrowRight size={17}/></button></div>}</section>
 </TabsContent>
 <TabsContent value="saved"><section className="saved-heading"><p className="eyebrow">THE ONES THAT STAY</p><h1>留下来的声音<span>{saved.length.toString().padStart(2,"0")}</span></h1><p>你亲手留下的歌。保存在当前浏览器，随时回来听。</p></section>{saved.length?<div className="saved-list">{saved.map((t,i)=><div className="saved-row" key={trackKey(t)}><span className="saved-number">{String(i+1).padStart(2,"0")}</span><button className="saved-cover" onClick={()=>play(t)} aria-label={`试听收藏 ${t.title}`}><img src={t.image} alt=""/><Play size={20}/></button><div className="saved-info"><h3>{t.title}</h3><p>{t.artist}</p></div><span className="saved-album">{t.album}</span><button className="outline-button" onClick={()=>choose(t)}>沿着这首找<ArrowRight size={15}/></button><button className="heart-button is-saved" onClick={()=>save(t)} aria-label={`取消收藏 ${t.title}`}><Heart fill="currentColor" size={18}/></button></div>)}</div>:<div className="empty-state"><Heart size={32}/><h3>还没有留下的歌</h3><p>听到心动的那一首，点一下爱心。</p><button onClick={()=>setView("discover")}>去发现音乐 <ArrowRight size={16}/></button></div>}</TabsContent>
 </Tabs>
 <footer className="page-footer"><span>好音乐，值得偶遇。</span><Dialog><DialogTrigger className="about-link">关于余音 <Info size={13}/></DialogTrigger><DialogContent className="about-dialog"><DialogTitle>让下一次偶遇，更有方向。</DialogTitle><DialogDescription>余音 · Aftertone</DialogDescription><p>从你喜欢的歌曲出发，结合艺术家关联、专辑类型和明确偏好，由 Jev 筛选值得试听的作品。</p><p>Jev 读取的是歌曲资料，不能直接听音频。这里的推荐是试听线索，不是对“好听”的保证；暂不支持按歌曲片段分析听感。</p><p>曲目资料与试听来自 Deezer；部分华语搜索由 iTunes 补充。试听可能受地区与歌曲供应情况影响，完整歌曲请前往对应音乐平台收听。</p><p>收藏和“不太合适”保存在当前浏览器。每次找歌会将所选歌曲、补充偏好及最近最多 8 首正负反馈交给 Jev 处理。每日最多 30 轮筛选。</p><a href="https://docs.typesafe.ai/concepts/state" target="_blank" rel="noreferrer">了解 Jev 的能力 <ArrowUpRight size={14}/></a>{dismissed.length>0&&<button className="outline-button" onClick={()=>{setDismissed([]);setToast("已清空不合适记录");}}>重置不合适记录（{dismissed.length}）<RotateCcw size={14}/></button>}</DialogContent></Dialog><span>AFTERTONE / VOL. 001</span></footer>
 <audio ref={audioRef} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onLoadedMetadata={e=>setDuration(Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:30)} onError={()=>{if(audioRef.current?.getAttribute("src")){setPlaying(false);setError("试听暂时无法播放，可点击音乐平台链接收听。");}}} preload="none"/>
 <div className="player-bar">{current?<><div className="player-track"><img src={current.image} alt=""/><div><strong>{current.title}</strong><span>{current.artist}</span></div><button className={`heart-button ${isSaved(current)?"is-saved":""}`} aria-label={`${isSaved(current)?"取消收藏":"收藏"}正在试听的歌曲`} onClick={()=>save(current)}><Heart size={17} fill={isSaved(current)?"currentColor":"none"}/></button></div><div className="transport"><button className="transport-play" onClick={()=>play(current)} aria-label={playing?"暂停试听":"继续试听"} disabled={!!loadingTrack}>{loadingTrack?<LoaderCircle className="spin" size={19}/>:playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><span className="time">{seconds(position)}</span><Slider aria-label="试听进度" value={[position]} max={duration||30} step={.1} onValueChange={([v])=>{if(audioRef.current&&audioRef.current.readyState>0){audioRef.current.currentTime=v;setPosition(v);}}}/><span className="time">{seconds(duration)}</span></div><div className="player-extras"><div className="volume-control"><Volume2 size={17}/><Slider aria-label="音量" value={[volume]} min={0} max={1} step={.05} onValueChange={([v])=>{setVolume(v);if(audioRef.current)audioRef.current.volume=v;}}/></div><a href={current.url} target="_blank" rel="noreferrer">听完整首<ArrowUpRight size={15}/></a></div></>:<><div className="player-idle"><AudioLines size={24}/><span>选一首歌，开始试听</span></div><span className="player-caption">短暂试听 · 喜欢就去听完整首</span></>}</div>
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
 </main>;
}
