/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker/env.d.ts --config wrangler.api.jsonc --env-interface AftertoneApiEnv --include-runtime false --strict-vars=false` (hash: 457f41139eeb82cc1fb67f443ea33fc8)
interface __BaseEnv_AftertoneApiEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	ALLOWED_ORIGINS: string;
	CANDIDATE_LIMIT: string;
	SITE_DAILY_ROUNDS: string;
	PERSONAL_DAILY_ROUNDS: string;
	IP_DAILY_ROUNDS: string;
	PERSONAL_GLOBAL_DAILY_ROUNDS: string;
	ITUNES_COUNTRY: string;
	TYPESAFE_API_KEY: string;
	JOB_RUNNER: DurableObjectNamespace<import("./main").JobRunner>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
		durableNamespaces: "JobRunner";
	}
	interface Env extends __BaseEnv_AftertoneApiEnv {}
}
interface AftertoneApiEnv extends __BaseEnv_AftertoneApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "CANDIDATE_LIMIT" | "SITE_DAILY_ROUNDS" | "PERSONAL_DAILY_ROUNDS" | "IP_DAILY_ROUNDS" | "PERSONAL_GLOBAL_DAILY_ROUNDS" | "ITUNES_COUNTRY" | "TYPESAFE_API_KEY">> {}
}
