/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker/env.d.ts --config wrangler.api.jsonc --env-interface AftertoneApiEnv --include-runtime false` (hash: 0d96c22e52f464419e59a6e946a932e3)
interface __BaseEnv_AftertoneApiEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	TYPESAFE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_AftertoneApiEnv {}
}
interface AftertoneApiEnv extends __BaseEnv_AftertoneApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TYPESAFE_API_KEY">> {}
}
